# Generated by Django 5.1.3 on 2024-12-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='descritipion',
            new_name='descripition',
        ),
    ]
