# Generated by Django 5.1.3 on 2024-11-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='descritipion',
            new_name='description',
        ),
    ]
